
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hugo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        lblRes.setVisible(false);
        segredo.setVisible(false);
        lblPensar.setText("<html>Estou a pensar num valor entre <strong>1 e 10</strong>....Tenta adivinhar....</htmal>");
        lblPensar.setFont (new Font ("Arial Black",Font.PLAIN,16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        segredo = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        lblPensar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        entrada = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        lblRes = new javax.swing.JLabel();
        btnCheat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        segredo.setText("segr");
        getContentPane().add(segredo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 130, 90));

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FB_20170204_12_16_37_Saved_Picture.jpg"))); // NOI18N
        foto.setText("jLabel1");
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 579, 382));

        lblPensar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPensar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPensar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblPensar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblPensar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 160, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/47e978f1ced878f94a51c27b9e2e7370.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 230, 240));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Valor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 81, 108, 50));

        entrada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        entrada.setModel(new javax.swing.SpinnerNumberModel(1, null, 10, 1));
        getContentPane().add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 82, 57, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Palpite");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 169, 130, 56));

        lblRes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRes.setText("<resultado>");
        getContentPane().add(lblRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, 65));

        btnCheat.setText("cheat");
        btnCheat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheatActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheat, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double ale = Math.random();
        int numero_gerado = (int) (1 + ale*(11-1));//1 a 10
        int aposta = Integer.parseInt( entrada.getValue().toString());
        String resultado = (numero_gerado==aposta)?"<html>Boa acertou, era mesmo o "+numero_gerado+ "</html>":"<html>Falhou, era o "+numero_gerado+"</html>";
        lblRes.setText(resultado);
        segredo.setText(Integer.toString(numero_gerado));
        lblRes.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCheatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheatActionPerformed
        // TODO add your handling code here:
        segredo.setVisible(true);
    }//GEN-LAST:event_btnCheatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheat;
    private javax.swing.JSpinner entrada;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblPensar;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel segredo;
    // End of variables declaration//GEN-END:variables
}
